# Ansible pipeline
# Tesing

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  displayName: 'Install Python'
  inputs:
    versionSpec: '3.10'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'rpacoe_staging'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
            az account show --query="id" -o tsv

- script: pip install ansible
  displayName: 'Install Ansible'

- script: pip install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
  displayName: 'Install Azure modules needed'

- script: ansible-galaxy collection install azure.azcollection
  displayName: 'Install Ansible Azure Collection'
  
- script: ansible-playbook -i 'bazeausrpan05,' site.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_CLIENT_ID: $(ARM_CLIENT_ID)
    AZURE_SECRET: $(ARM_CLIENT_SECRET)
    AZURE_TENANT: $(ARM_TENANT_ID)
    AZURE_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
